# -*- coding: utf-8 -*-
"""finalproject

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRJHWjQIA2w3slDfOqW6x3ZRF6FrlXHq
"""

import matplotlib.pyplot as plt


total = 132

gender_data = {
    'Male': 60,
    'Female': 72
}

college_data = {
    'Engineering': 36,
    'Management': 46,
    'Medicine': 50
}

note_taking_data = {
    'Taking Notes in class': 86,
    'Pay attention in class and review the material afterwards': 46
}

gender_labels = ['Male', 'Female']
college_labels = ['Engineering', 'Management', 'Medicine']
note_taking_labels = ['Taking Notes in class', 'Pay attention in class and review the material afterwards']


plt.figure(figsize=(6, 6))
plt.pie(gender_data.values(), labels=gender_labels, autopct='%1.1f%%')
plt.title('Gender Distribution')
plt.show()


plt.figure(figsize=(6, 6))
plt.pie(college_data.values(), labels=college_labels, autopct='%1.1f%%')
plt.title('College Distribution')
plt.show()


plt.figure(figsize=(6, 6))
plt.pie(note_taking_data.values(), labels=note_taking_labels, autopct='%1.1f%%')
plt.title('Note-taking Preferences')
plt.show()

total = 132
taking_notes = 86
no_notes = 46

taking_notes_percentage = (taking_notes / total) * 100
no_notes_percentage = (no_notes / total) * 100

labels = ['Taking Notes in class in class', 'Pay attention in class and review the material afterwards']
sizes = [taking_notes_percentage, no_notes_percentage]
colors = ['lightblue', 'lightpink']
explode = (0.1, 0)  

plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')  
plt.title('Note-taking Preferences')
plt.show()

print(f'Total: {total}')
print(f'Taking Notes in class in class: {taking_notes} ({taking_notes_percentage:.1f}%)')
print(f'Pay attention in class and review the material afterwards: {no_notes} ({no_notes_percentage:.1f}%)')

male_total = 60
male_taking_notes = 37
male_no_notes = 23

female_total = 72
female_taking_notes = 49
female_no_notes = 23


male_taking_notes_percentage = (male_taking_notes / male_total) * 100
male_no_notes_percentage = (male_no_notes / male_total) * 100

female_taking_notes_percentage = (female_taking_notes / female_total) * 100
female_no_notes_percentage = (female_no_notes / female_total) * 100


labels = ['Taking Notes in class', 'Pay attention in class and review the material afterwards']
male_sizes = [male_taking_notes_percentage, male_no_notes_percentage]
female_sizes = [female_taking_notes_percentage, female_no_notes_percentage]
colors = ['lightblue', 'lightpink']
explode = (0.1, 0)  


plt.figure(figsize=(6, 6))
plt.pie(male_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Male')
plt.show()


plt.figure(figsize=(6, 6))
plt.pie(female_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Female')
plt.show()


print('Male:')
print(f'Total: {male_total}')
print(f'Taking Notes in class: {male_taking_notes} ({male_taking_notes_percentage:.1f}%)')
print(f'Pay attention in class and review the material afterwards: {male_no_notes} ({male_no_notes_percentage:.1f}%)\n')

print('Female:')
print(f'Total: {female_total}')
print(f'Taking Notes in class: {female_taking_notes} ({female_taking_notes_percentage:.1f}%)')
print(f'Pay attention in class and review the material afterwards: {female_no_notes} ({female_no_notes_percentage:.1f}%)')

engineering_total = 36
engineering_no_notes = 16
engineering_taking_notes = 20

management_total = 46
management_no_notes = 14
management_taking_notes = 32

medicine_total = 50
medicine_no_notes = 16
medicine_taking_notes = 34


engineering_no_notes_percentage = (engineering_no_notes / engineering_total) * 100
engineering_taking_notes_percentage = (engineering_taking_notes / engineering_total) * 100

management_no_notes_percentage = (management_no_notes / management_total) * 100
management_taking_notes_percentage = (management_taking_notes / management_total) * 100

medicine_no_notes_percentage = (medicine_no_notes / medicine_total) * 100
medicine_taking_notes_percentage = (medicine_taking_notes / medicine_total) * 100


labels = ['Taking Notes in class', 'Pay attention in class and review the material afterwards']
colors = ['lightblue', 'lightpink']
explode = (0.1, 0)  


engineering_sizes = [engineering_taking_notes_percentage, engineering_no_notes_percentage]
plt.figure(figsize=(6, 6))
plt.pie(engineering_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Engineering')
plt.show()


management_sizes = [management_taking_notes_percentage, management_no_notes_percentage]
plt.figure(figsize=(6, 6))
plt.pie(management_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Management')
plt.show()


medicine_sizes = [medicine_taking_notes_percentage, medicine_no_notes_percentage]
plt.figure(figsize=(6, 6))
plt.pie(medicine_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Medicine')
plt.show()


print('Engineering:')
print(f'Total: {engineering_total}')
print(f'Taking Notes in class: {engineering_taking_notes} ({engineering_taking_notes_percentage:.1f}%)')
print(f'Pay attention in class and review the material afterwards: {engineering_no_notes} ({engineering_no_notes_percentage:.1f}%)\n')

print('Management:')
print(f'Total: {management_total}')
print(f'Taking Notes in class: {management_taking_notes} ({management_taking_notes_percentage:.1f}%)')
print(f'Pay attention in class and review the material afterwards: {management_no_notes} ({management_no_notes_percentage:.1f}%)\n')

print('Medicine:')
print(f'Total: {medicine_total}')
print(f'Taking Notes in class: {medicine_taking_notes} ({medicine_taking_notes_percentage:.1f}%)')
print(f'Pay attention in class and review the material afterwards: {medicine_no_notes} ({medicine_no_notes_percentage:.1f}%)')

total = 132
paper_based = 83
electronic = 49


paper_based_percentage = (paper_based / total) * 100
electronic_percentage = (electronic / total) * 100


labels = ['Paper notes', 'Digital notes']
sizes = [paper_based_percentage, electronic_percentage]
colors = ['lightblue', 'lightpink']
explode = (0.1, 0)  

plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')  
plt.title('Note-taking Preferences: Paper notes vs Digital notes')
plt.show()


print(f'Total: {total}')
print(f'Paper notes: {paper_based} ({paper_based_percentage:.1f}%)')
print(f'Digital notes: {electronic} ({electronic_percentage:.1f}%)')

male_total = 60
male_paper_based = 44
male_electronic = 16

female_total = 72
female_paper_based = 39
female_electronic = 33


male_paper_based_percentage = (male_paper_based / male_total) * 100
male_electronic_percentage = (male_electronic / male_total) * 100

female_paper_based_percentage = (female_paper_based / female_total) * 100
female_electronic_percentage = (female_electronic / female_total) * 100


labels = ['Paper notes', 'Digital notes']
colors = ['lightblue', 'lightpink']
explode = (0.1, 0)  


male_sizes = [male_paper_based_percentage, male_electronic_percentage]
plt.figure(figsize=(6, 6))
plt.pie(male_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences: Paper notes vs Digital notes- Male')
plt.show()


female_sizes = [female_paper_based_percentage, female_electronic_percentage]
plt.figure(figsize=(6, 6))
plt.pie(female_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences: Paper notes vs Digital notes - Female')
plt.show()


print('Male:')
print(f'Total: {male_total}')
print(f'Paper notes: {male_paper_based} ({male_paper_based_percentage:.1f}%)')
print(f'Digital notes: {male_electronic} ({male_electronic_percentage:.1f}%)\n')

print('Female:')
print(f'Total: {female_total}')
print(f'Paper notes: {female_paper_based} ({female_paper_based_percentage:.1f}%)')
print(f'Digital notes: {female_electronic} ({female_electronic_percentage:.1f}%)')

engineering_total = 36
engineering_paper_based = 31
engineering_electronic = 5

management_total = 46
management_paper_based = 29
management_electronic = 17

medicine_total = 50
medicine_paper_based = 23
medicine_electronic = 27


engineering_paper_based_percentage = (engineering_paper_based / engineering_total) * 100
engineering_electronic_percentage = (engineering_electronic / engineering_total) * 100

management_paper_based_percentage = (management_paper_based / management_total) * 100
management_electronic_percentage = (management_electronic / management_total) * 100

medicine_paper_based_percentage = (medicine_paper_based / medicine_total) * 100
medicine_electronic_percentage = (medicine_electronic / medicine_total) * 100


labels = ['Paper notes', 'Digital notes']
colors = ['lightblue', 'lightpink']
explode = (0.1, 0)  


engineering_sizes = [engineering_paper_based_percentage, engineering_electronic_percentage]
plt.figure(figsize=(6, 6))
plt.pie(engineering_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Engineering')
plt.show()


management_sizes = [management_paper_based_percentage, management_electronic_percentage]
plt.figure(figsize=(6, 6))
plt.pie(management_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Management')
plt.show()


medicine_sizes = [medicine_paper_based_percentage, medicine_electronic_percentage]
plt.figure(figsize=(6, 6))
plt.pie(medicine_sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title('Note-taking Preferences - Medicine')
plt.show()


print('Engineering:')
print(f'Total: {engineering_total}')
print(f'Paper notes: {engineering_paper_based} ({engineering_paper_based_percentage:.1f}%)')
print(f'Digital notes: {engineering_electronic} ({engineering_electronic_percentage:.1f}%)\n')

print('Management:')
print(f'Total: {management_total}')
print(f'Paper notes: {management_paper_based} ({management_paper_based_percentage:.1f}%)')
print(f'Digital notes: {management_electronic} ({management_electronic_percentage:.1f}%)\n')

print('Medicine:')
print(f'Total: {medicine_total}')
print(f'Paper notes: {medicine_paper_based} ({medicine_paper_based_percentage:.1f}%)')
print(f'Digital notes: {medicine_electronic} ({medicine_electronic_percentage:.1f}%)')